export const TEST_PAGE = 'TEST_PAGE'
export const TEST_PAGE_ORDER = 'TEST_PAGE_ORDER'
export const TEST_PAGE_SIMULATEEXAM = 'TEST_PAGE_SIMULATEEXAM'
export const TEST_PAGE_ALLSIMULATE = 'TEST_PAGE_ALLSIMULATE'

